[[redirects]]
  from = "/aisis"
  to = "https://aisis.ateneo.edu/"
  status = 200
  force = true

[[redirects]]
  from = "/aisis/*"
  to = "https://aisis.ateneo.edu/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/aisis/*"
  to = "https://aisis.ateneo.edu/j_aisis/displayLogin.do:splat"
  status = 200
  force = true
